(function(){
  const cfg=window.FANTASMAS_SUPABASE;let db=null,loaded=false;
  function money(v){return new Intl.NumberFormat('es-MX',{maximumFractionDigits:0}).format(Number(v||0));}
  function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
  function ensureClient(){if(db)return db;if(window.supabase?.createClient&&cfg?.url&&cfg?.publishableKey)db=window.supabase.createClient(cfg.url,cfg.publishableKey);return db;}
  function conversion(summary){const starts=Number(summary.checkout_starts||0),success=Number(summary.checkout_success||0);return starts?Math.round(success/starts*100):0;}
  async function load(){const client=ensureClient();const panel=document.querySelector('#growthAnalytics');if(!client||!panel||document.querySelector('#adminApp')?.hidden)return;panel.classList.add('loading');try{const {data,error}=await client.rpc('shop_analytics_summary',{p_days:30});if(error)throw error;const s=data||{};panel.querySelector('[data-ga="sessions"]').textContent=money(s.sessions);panel.querySelector('[data-ga="views"]').textContent=money(s.product_views);panel.querySelector('[data-ga="cart"]').textContent=money(s.add_to_cart);panel.querySelector('[data-ga="conversion"]').textContent=`${conversion(s)}%`;panel.querySelector('#growthSearches').innerHTML=(s.top_searches||[]).length?(s.top_searches||[]).map(x=>`<li><span>${esc(x.query)}</span><b>${money(x.n)}</b></li>`).join(''):'<li><span>Aún no hay búsquedas registradas</span></li>';panel.querySelector('#growthProducts').innerHTML=(s.top_products||[]).length?(s.top_products||[]).map(x=>`<li><span>${esc(x.name)}</span><b>${money(x.views)} vistas</b></li>`).join(''):'<li><span>Aún no hay vistas de producto registradas</span></li>';panel.querySelector('#growthMeta').textContent=`Últimos 30 días · ${money(s.events)} eventos medidos`;loaded=true;}catch(e){panel.querySelector('#growthMeta').textContent='La analítica empezará a llenarse después de publicar esta actualización.';}finally{panel.classList.remove('loading');}}
  document.addEventListener('DOMContentLoaded',()=>{const timer=setInterval(()=>{if(!document.querySelector('#adminApp')?.hidden){clearInterval(timer);load();}},500);document.querySelectorAll('.refresh-data').forEach(b=>b.addEventListener('click',()=>setTimeout(load,400)));document.querySelector('#refreshGrowth')?.addEventListener('click',load);});
})();
