create table if not exists public.shop_analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  session_id uuid,
  product_id uuid references public.shop_products(id) on delete set null,
  order_id uuid references public.shop_orders(id) on delete set null,
  query text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint shop_analytics_event_type_chk check (event_type in (
    'page_view','catalog_search','product_view','add_to_cart','remove_from_cart',
    'checkout_start','checkout_success','checkout_error','coupon_apply','whatsapp_click','share_product'
  )),
  constraint shop_analytics_query_len_chk check (query is null or char_length(query) <= 180)
);

create index if not exists shop_analytics_events_created_idx on public.shop_analytics_events(created_at desc);
create index if not exists shop_analytics_events_type_created_idx on public.shop_analytics_events(event_type,created_at desc);
create index if not exists shop_analytics_events_product_idx on public.shop_analytics_events(product_id,created_at desc) where product_id is not null;
alter table public.shop_analytics_events enable row level security;

create or replace function public.track_shop_event(
  p_event_type text,
  p_session_id uuid default null,
  p_product_id uuid default null,
  p_order_id uuid default null,
  p_query text default null,
  p_metadata jsonb default '{}'::jsonb
) returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare v_count integer;
begin
  if p_event_type not in ('page_view','catalog_search','product_view','add_to_cart','remove_from_cart','checkout_start','checkout_success','checkout_error','coupon_apply','whatsapp_click','share_product') then
    return false;
  end if;
  if p_session_id is not null then
    select count(*) into v_count from public.shop_analytics_events
      where session_id=p_session_id and created_at>now()-interval '1 hour';
    if v_count >= 180 then return false; end if;
  end if;
  insert into public.shop_analytics_events(event_type,session_id,product_id,order_id,query,metadata)
  values(
    p_event_type,p_session_id,p_product_id,p_order_id,
    nullif(left(trim(coalesce(p_query,'')),180),''),
    case when jsonb_typeof(coalesce(p_metadata,'{}'::jsonb))='object' then coalesce(p_metadata,'{}'::jsonb) else '{}'::jsonb end
  );
  return true;
end;
$$;
revoke all on function public.track_shop_event(text,uuid,uuid,uuid,text,jsonb) from public;
grant execute on function public.track_shop_event(text,uuid,uuid,uuid,text,jsonb) to anon,authenticated,service_role;

create or replace function public.shop_analytics_summary(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_from timestamptz:=now()-make_interval(days=>greatest(1,least(365,p_days)));
  v_result jsonb;
begin
  if not public.is_shop_admin() then raise exception 'Acceso administrativo requerido'; end if;
  select jsonb_build_object(
    'days',greatest(1,least(365,p_days)),
    'events',count(*),
    'sessions',count(distinct session_id),
    'product_views',count(*) filter(where event_type='product_view'),
    'add_to_cart',count(*) filter(where event_type='add_to_cart'),
    'checkout_starts',count(*) filter(where event_type='checkout_start'),
    'checkout_success',count(*) filter(where event_type='checkout_success'),
    'whatsapp_clicks',count(*) filter(where event_type='whatsapp_click'),
    'top_searches',coalesce((
      select jsonb_agg(x order by x.n desc) from (
        select query, count(*)::integer n from public.shop_analytics_events
        where created_at>=v_from and event_type='catalog_search' and query is not null
        group by query order by count(*) desc limit 10
      ) x
    ),'[]'::jsonb),
    'top_products',coalesce((
      select jsonb_agg(x order by x.views desc) from (
        select p.id,p.name,count(*)::integer views
        from public.shop_analytics_events e join public.shop_products p on p.id=e.product_id
        where e.created_at>=v_from and e.event_type='product_view'
        group by p.id,p.name order by count(*) desc limit 10
      ) x
    ),'[]'::jsonb)
  ) into v_result
  from public.shop_analytics_events where created_at>=v_from;
  return v_result;
end;
$$;
revoke all on function public.shop_analytics_summary(integer) from public;
grant execute on function public.shop_analytics_summary(integer) to authenticated,service_role;

create or replace function public.shop_product_available_stock(p_product_id uuid)
returns integer
language sql
stable
security definer
set search_path=''
as $$
  select case when p.stock is null then null else greatest(0,p.stock-coalesce((
    select sum(r.quantity)::integer from public.shop_product_reservations r
    where r.product_id=p.id and r.status='active' and r.reserved_until>now()
  ),0)) end
  from public.shop_products p where p.id=p_product_id and p.active=true;
$$;
revoke all on function public.shop_product_available_stock(uuid) from public;
grant execute on function public.shop_product_available_stock(uuid) to anon,authenticated,service_role;
