(async function(){
  const cfg=window.FANTASMAS_SUPABASE;const root=document.querySelector('#productPage');
  if(!window.supabase?.createClient||!cfg?.url||!cfg?.publishableKey){root.innerHTML='<div class="product-error">No se pudo conectar con la tienda.</div>';return;}
  const db=window.supabase.createClient(cfg.url,cfg.publishableKey);window.FANTASMAS_DB=db;
  const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const params=new URLSearchParams(location.search);const id=params.get('id');const sku=params.get('sku');
  const activeNow=(x,now=Date.now())=>x.active!==false&&(!x.starts_at||new Date(x.starts_at).getTime()<=now)&&(!x.ends_at||new Date(x.ends_at).getTime()>=now);
  const sortPromos=list=>[...list].sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0)||String(a.created_at||'').localeCompare(String(b.created_at||''))||String(a.id||'').localeCompare(String(b.id||'')));
  const matches=(p,x)=>p.scope==='products'?(p.product_ids||[]).includes(x.id):p.scope==='categories'?(p.category_names||[]).includes(x.category):true;
  const apply=(v,t,n)=>t==='percentage'?Math.max(0,v*(1-Math.min(100,Number(n))/100)):Math.max(0,v-Number(n));
  function offer(product,promos){let price=Number(product.price),applied=[];sortPromos(promos).forEach(p=>{if(!activeNow(p)||!matches(p,product)||Number(product.price)<Number(p.minimum_purchase||0))return;price=apply(price,p.discount_type,p.discount_value);applied.push(p.title||'Promoción');});return{original:Number(product.price),price:Math.round(price*100)/100,applied};}
  function session(){const k='fantasmas_shop_analytics_session_v1';try{let x=localStorage.getItem(k);if(!x){x=crypto.randomUUID();localStorage.setItem(k,x);}return x;}catch{return crypto.randomUUID();}}
  async function track(type,productId,metadata={}){try{await db.rpc('track_shop_event',{p_event_type:type,p_session_id:session(),p_product_id:productId,p_order_id:null,p_query:null,p_metadata:metadata});}catch{}}
  function toast(t){const e=document.querySelector('#productToast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300);}
  function addCart(product,price,stock){const key='fantasmas_shop_cart_v1';let cart=[];try{cart=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(cart))cart=[];}catch{}const existing=cart.find(x=>x.id===product.id);const max=stock==null?20:Number(stock);if(existing)existing.quantity=Math.min(max,Number(existing.quantity||0)+1);else cart.push({id:product.id,kind:'product',cart_key:product.id,name:product.name,price:Number(price),image_url:product.image_url||'',stock:stock,quantity:1});localStorage.setItem(key,JSON.stringify(cart));track('add_to_cart',product.id,{source:'product_page'});toast('Producto agregado al carrito.');}
  try{
    let q=db.from('shop_products').select('*').eq('active',true).limit(1);q=id?q.eq('id',id):sku?q.eq('sku',sku):q.eq('id','00000000-0000-0000-0000-000000000000');
    const [{data:rows,error},{data:promos},{data:settings}]=await Promise.all([q,db.from('shop_promotions').select('*').eq('active',true),db.from('shop_settings').select('setting_value').eq('setting_key','store_info').maybeSingle()]);
    if(error)throw error;const product=rows?.[0];if(!product){root.innerHTML='<div class="product-error"><h1>Producto no disponible</h1><p>Puede haberse agotado o retirado del catálogo.</p><a class="back" href="index.html#productosPublicos">Volver al catálogo</a></div>';return;}
    const [{data:availableStock}]=await Promise.all([db.rpc('shop_product_available_stock',{p_product_id:product.id})]);
    const stock=availableStock===undefined?product.stock:availableStock;const price=offer(product,promos||[]);const canBuy=product.online_sale!==false&&(stock==null||Number(stock)>0);
    const store=settings?.setting_value||{};let wa=String(store.whatsapp||'5610329215').replace(/\D/g,'');if(wa.length===10)wa='52'+wa;
    document.title=`${product.name} | Fantasmas Biker's Shop`;document.querySelector('meta[name="description"]').content=(product.description||`${product.name} disponible en Fantasmas Biker's Shop`).slice(0,155);
    const og=document.createElement('meta');og.setAttribute('property','og:title');og.content=product.name;document.head.appendChild(og);if(product.image_url){const m=document.createElement('meta');m.setAttribute('property','og:image');m.content=product.image_url;document.head.appendChild(m);}
    const jsonld=document.createElement('script');jsonld.type='application/ld+json';jsonld.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description||'',image:product.image_url?[product.image_url]:undefined,sku:product.sku||undefined,offers:{'@type':'Offer',price:price.price,priceCurrency:'MXN',availability:canBuy?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:location.href}});document.head.appendChild(jsonld);
    root.innerHTML=`<article class="product-shell"><div class="product-photo">${product.image_url?`<img src="${esc(product.image_url)}" alt="${esc(product.name)}">`:'<span class="no-image">☠</span>'}</div><div class="product-info"><div class="product-kicker">${esc(product.category||'CATÁLOGO')}</div><h1>${esc(product.name)}</h1><p class="product-desc">${esc(product.description||'Consulta disponibilidad y detalles directamente con Fantasmas Biker\'s Shop.')}</p><div class="price-box"><div class="price-line">${price.price<price.original?`<del>${money(price.original)}</del>`:''}<strong>${money(price.price)}</strong>${price.applied.length?'<span class="offer-pill">OFERTA VIGENTE</span>':''}</div>${price.applied.length?`<ul class="promo-list">${price.applied.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div><div class="stock ${canBuy?'':'out'}">${stock==null?'Disponible':Number(stock)>0?`${stock} disponible${Number(stock)===1?'':'s'} ahora`:'Agotado por ahora'}</div><div class="product-actions">${canBuy?'<button id="addProduct" class="primary" type="button">Agregar al carrito</button><button id="buyProduct" class="secondary" type="button">Comprar ahora</button>':`<a class="primary" target="_blank" rel="noopener" href="https://wa.me/${wa}?text=${encodeURIComponent('Hola, quiero consultar disponibilidad de '+product.name)}">Consultar por WhatsApp</a>`}<button id="shareProduct" class="ghost" type="button">Compartir producto</button><a class="ghost" href="index.html#productosPublicos">Seguir comprando</a></div><div class="product-meta">${product.sku?`<span>SKU: ${esc(product.sku)}</span>`:''}<span>Precio y promociones verificados al abrir esta página.</span><span>Las existencias pueden cambiar mientras completas tu compra.</span></div></div></article>`;
    document.querySelector('#addProduct')?.addEventListener('click',()=>addCart(product,price.price,stock));document.querySelector('#buyProduct')?.addEventListener('click',()=>{addCart(product,price.price,stock);location.href='index.html?openCart=1';});document.querySelector('#shareProduct')?.addEventListener('click',async()=>{const data={title:product.name,text:`${product.name} · Fantasmas Biker's Shop`,url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Enlace copiado.');}track('share_product',product.id,{source:'product_page'});}catch{}});
    track('product_view',product.id,{source:'product_page'});
    const {data:related}=await db.from('shop_products').select('id,name,category,price,image_url').eq('active',true).eq('category',product.category).neq('id',product.id).limit(4);if(related?.length){document.querySelector('#relatedGrid').innerHTML=related.map(x=>`<a class="related-card" href="producto.html?id=${encodeURIComponent(x.id)}"><img src="${esc(x.image_url||'logo-shop.png')}" alt="${esc(x.name)}" loading="lazy"><div><small>${esc(x.category||'')}</small><b>${esc(x.name)}</b><strong>${money(x.price)}</strong></div></a>`).join('');document.querySelector('#relatedSection').hidden=false;}
    if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
  }catch(e){console.error(e);root.innerHTML='<div class="product-error"><h1>No pudimos cargar este producto.</h1><p>Actualiza la página o vuelve al catálogo.</p><a class="back" href="index.html#productosPublicos">Volver al catálogo</a></div>';}
})();
