(async function(){
  const config=window.FANTASMAS_SUPABASE||{};const $=s=>document.querySelector(s);const raffleId=new URLSearchParams(location.search).get("id");const client=window.supabase?.createClient(config.url,config.publishableKey);let raffle=null,numbers=[],selected=null,prizes=[];
  const fail=m=>{document.body.innerHTML=`<main class="control-main"><h1>No se pudo abrir el control</h1><p>${m}</p><a href="admin.html">Volver al panel</a></main>`};
  if(!client||!/^[0-9a-f-]{36}$/i.test(raffleId||""))return fail("Rifa inválida.");
  const {data:{session}}=await client.auth.getSession();if(!session)return location.href="admin.html";
  const {data:admin}=await client.from("shop_admins").select("user_id").eq("user_id",session.user.id).maybeSingle();if(!admin)return fail("Tu sesión no tiene permiso de administrador.");
  const {data:r}=await client.from("shop_raffles").select("*").eq("id",raffleId).maybeSingle();if(!r)return fail("No encontramos esa rifa.");raffle=r;
  $("#raffleName").textContent=raffle.main_prize;$("#publicRaffleLink").href=`rifa.html?id=${raffleId}`;$("#broadcastLink").href=`sorteo-en-vivo.html?id=${raffleId}`;
  prizes=String(raffle.secondary_prizes||"").split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);prizes.push(raffle.main_prize);$("#prizeSelect").innerHTML=prizes.map((p,i)=>`<option value="${i+1}">${i+1}. ${p}${i===prizes.length-1?" · PRINCIPAL":""}</option>`).join("");
  const esc=v=>String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
  async function loadNumbers(){const {data,error}=await client.rpc("admin_shop_raffle_numbers",{p_raffle_id:raffleId});if(error)throw error;numbers=data||[];renderNumbers();}
  function renderNumbers(){const counts={available:0,reserved:0,paid:0,blocked:0,winner:0};numbers.forEach(n=>counts[n.status]=(counts[n.status]||0)+1);$("#raffleStats").innerHTML=`<span>${numbers.length} totales</span><span>${counts.available} disponibles</span><span>${counts.reserved} reservados</span><span>${counts.paid} pagados</span><span>${counts.winner} ganadores</span>`;$("#toggleSales").textContent=raffle.sales_open?"Cerrar venta":"Abrir venta";$("#adminNumberMap").innerHTML=numbers.map(n=>`<button data-number="${n.number}" class="${n.status}${selected===n.number?" active":""}" title="${esc(n.customer_name||n.status)}">${String(n.number).padStart(2,"0")}</button>`).join("");}
  function selectNumber(n){selected=n;const row=numbers.find(x=>x.number===n);$("#selectedAdminNumber").textContent=String(n).padStart(2,"0");$("#walkinName").value=row?.customer_name||"";$("#walkinPhone").value=row?.customer_phone||"";$("#walkinEmail").value=row?.customer_email||"";$("#numberStatus").textContent=`Estado actual: ${row?.status||"disponible"}`;renderNumbers();}
  async function setNumber(action){if(!selected)return $("#numberStatus").textContent="Primero selecciona un número.";$("#numberStatus").textContent="Guardando…";const {error}=await client.rpc("admin_set_shop_raffle_number",{p_raffle_id:raffleId,p_number:selected,p_action:action,p_customer_name:$("#walkinName").value,p_customer_phone:$("#walkinPhone").value,p_customer_email:$("#walkinEmail").value});if(error)return $("#numberStatus").textContent=error.message;await loadNumbers();selectNumber(selected);$("#numberStatus").textContent="Cambio guardado.";}
  async function setPhase(phase){const order=Number($("#prizeSelect").value);const prize=prizes[order-1];const {error}=await client.rpc("set_shop_raffle_live_phase",{p_raffle_id:raffleId,p_phase:phase,p_prize:prize,p_prize_order:order});$("#drawFeedback").textContent=error?error.message:"Pantalla en vivo actualizada.";}
  async function loadDraws(){const {data}=await client.from("shop_raffle_draws").select("*").eq("raffle_id",raffleId).order("prize_order");$("#drawResults").innerHTML=(data||[]).length?(data||[]).map(d=>`<article><span>${esc(d.prize_name)}</span><strong>#${String(d.winning_number).padStart(2,"0")} · ${esc(d.public_winner)}</strong></article>`).join(""):"<p>Aún no hay ganadores.</p>";}
  $("#adminNumberMap").addEventListener("click",e=>{const b=e.target.closest("[data-number]");if(b)selectNumber(Number(b.dataset.number));});$("#markPaid").onclick=()=>setNumber("paid");$("#releaseNumber").onclick=()=>setNumber("release");$("#blockNumber").onclick=()=>setNumber("block");
  $("#toggleSales").onclick=async()=>{const {error}=await client.from("shop_raffles").update({sales_open:!raffle.sales_open,updated_at:new Date().toISOString()}).eq("id",raffleId);if(error)return alert(error.message);raffle.sales_open=!raffle.sales_open;renderNumbers();};
  $("#startCountdown").onclick=()=>setPhase("countdown");$("#spinWheel").onclick=()=>setPhase("spinning");$("#finishDraw").onclick=()=>setPhase("finished");
  $("#drawWinner").onclick=async()=>{const order=Number($("#prizeSelect").value);const prize=prizes[order-1];if(!confirm(`¿Sortear ahora el premio “${prize}”? Esta acción queda registrada.`))return;$("#drawFeedback").textContent="Seleccionando de forma segura entre los números pagados…";const {data,error}=await client.rpc("draw_shop_raffle_winner",{p_raffle_id:raffleId,p_prize_name:prize,p_prize_order:order});if(error)return $("#drawFeedback").textContent=error.message;$("#drawFeedback").textContent=`Ganador: número ${data.winning_number}.`;await Promise.all([loadNumbers(),loadDraws()]);};
  await Promise.all([loadNumbers(),loadDraws()]);
})();
