(function(){
  const $=(s)=>document.querySelector(s);let products=[];let cameraStream=null;let detector=null;
  const money=(v)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
  const clean=(v)=>String(v??"").replace(/^\uFEFF/,"").trim();
  function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell="";continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell="";continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const headers=rows.shift().map((x)=>clean(x).toLowerCase());return rows.map((values)=>Object.fromEntries(headers.map((h,i)=>[h,clean(values[i])]))).map((p)=>({name:p.name,sku:p.sku,barcode:p.barcode,price:p.price})).filter((p)=>p.name&&(p.barcode||p.sku));}
  function show(message,type=""){const el=$("#checkerStatus");el.textContent=message;el.className=`checker-status ${type}`}
  function renderCount(){$("#productCount").textContent=`${products.length} productos`}
  function lookup(code){const value=clean(code);$("#priceResult").hidden=true;$("#notFound").hidden=true;if(!value)return;const found=products.find((p)=>p.barcode===value||p.sku===value);if(!found){$("#notFound").hidden=false;show("Código no encontrado","error");return}$("#resultName").textContent=found.name;$("#resultCode").textContent=found.barcode||found.sku;$("#resultPrice").textContent=money(found.price);$("#priceResult").hidden=false;show("Producto encontrado","ok");$("#codeInput").select()}
  async function loadText(text){products=parseCsv(text);renderCount();show(products.length?`Lista cargada: ${products.length} productos.`:"El CSV no contiene productos válidos.",products.length?"ok":"error")}
  async function loadInitial(){try{const response=await fetch("products.csv",{cache:"no-store"});if(!response.ok)throw Error();await loadText(await response.text())}catch(_){show("Selecciona el CSV exportado de Aronium para cargar la lista.","error")}}
  async function startScan(){if(!( "BarcodeDetector"in window)){show("Tu navegador no permite escaneo automático. Escribe el código manualmente.","error");return}try{detector=new BarcodeDetector({formats:["ean_13","ean_8","code_128","code_39","upc_a","upc_e"]});cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});$("#cameraVideo").srcObject=cameraStream;$("#cameraBox").hidden=false;await $("#cameraVideo").play();scanFrame()}catch(error){show("No se pudo abrir la cámara. Revisa el permiso del navegador.","error")}}
  async function scanFrame(){if(!cameraStream)return;try{const codes=await detector.detect($("#cameraVideo"));if(codes[0]?.rawValue){$("#codeInput").value=codes[0].rawValue;stopScan();lookup(codes[0].rawValue);return}}catch(_){}requestAnimationFrame(scanFrame)}
  function stopScan(){cameraStream?.getTracks().forEach((track)=>track.stop());cameraStream=null;$("#cameraVideo").srcObject=null;$("#cameraBox").hidden=true}
  $("#lookupForm").addEventListener("submit",(e)=>{e.preventDefault();lookup($("#codeInput").value)});$("#scanButton").addEventListener("click",startScan);$("#stopScanButton").addEventListener("click",stopScan);$("#csvInput").addEventListener("change",async(e)=>{const file=e.target.files[0];if(file)await loadText(await file.text())});loadInitial();
})();
